### ISSUE TITLE
What is the Effect that uses "latestConnector" doing?

### ISSUE THREAD

**Issue by BrennerSpear** [shivkanthb/web3-starter#1]
https://github.com/shivkanthb/web3-starter/blob/dfcce037bf10f20817c1ae49bb79a32e74623cff/pages/index.js#L51

Since it only runs when the page loads, I don't really understand what it's for?

**Comment by shivkanthb** [comment]
The lastConnector is merely just to check what connector (injected or walletconnect) the user used last to connect their wallet. That was on page refresh, I can connect it back automatically (unless the user hit disconnect). Hope that clears it up for you.
